name: Compose Docker project

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up .NET Core environment
      #   run: |
      #     $env:PATH += ";${{ env.DotnetPath }}"
      #   env:
      #     DotnetPath: "C:/Program Files/dotnet"

      # - name: Add migration
      #   run: cd C:\actions-runner\Nhan\_work\Offline_Class_Robotic_Backend\Offline_Class_Robotic_Backend\OfficeClassRobotic dotnet ef --project OfficeClassRobotic.BuisnessObject --startup-project OfficeClassRobotic.API migrations add Initial1

      # - name: Update database
      #   run: cd C:\actions-runner\Nhan\_work\Offline_Class_Robotic_Backend\Offline_Class_Robotic_Backend\OfficeClassRobotic dotnet ef --project OfficeClassRobotic.BuisnessObject --startup-project OfficeClassRobotic.API database update

      # - name: Add migration
      #   shell: cmd
      #   run: |
      #     dotnet ef --project OfficeClassRobotic.BuisnessObject --startup-project OfficeClassRobotic.API migrations add Initial1

      # - name: Update database
      #   shell: cmd
      #   run: |
      #     dotnet ef --project OfficeClassRobotic.BuisnessObject --startup-project OfficeClassRobotic.API database update

      - name: Run Docker compose command
        run: docker compose up --build -d
